[package]
name = "awlyc-lexer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logos = "0.12.1"
text-size = "1.1.0"
smol_str = "0.1.23"

[dev-dependencies]
insta = "1.15.0"
paste = "1.0.7"