[package]
name = "awlyc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
text-size = "1.1.0"
smol_str = "0.1.23"
awlyc-parser = { path = "../awlyc-parser" }
awlyc-error = { path = "../awlyc-error" }